MATCH_SCHEDULE = [
    {"match": 1, "stage": "Group Stage", "group": "A", "date": "2026-06-11", "time": "15:00 ET", "team1": "Mexico", "team2": "South Africa", "venue": "Estadio Azteca, Mexico City"},
    {"match": 2, "stage": "Group Stage", "group": "A", "date": "2026-06-11", "time": "22:00 ET", "team1": "South Korea", "team2": "Czech Republic", "venue": "Estadio Akron, Guadalajara"},
    {"match": 3, "stage": "Group Stage", "group": "B", "date": "2026-06-12", "time": "15:00 ET", "team1": "Canada", "team2": "Bosnia & Herzegovina", "venue": "BMO Field, Toronto"},
    {"match": 4, "stage": "Group Stage", "group": "D", "date": "2026-06-12", "time": "21:00 ET", "team1": "United States", "team2": "Paraguay", "venue": "SoFi Stadium, Inglewood"},
    {"match": 5, "stage": "Group Stage", "group": "D", "date": "2026-06-13", "time": "00:00 ET", "team1": "Australia", "team2": "Turkey", "venue": "BC Place, Vancouver"},
    {"match": 6, "stage": "Group Stage", "group": "B", "date": "2026-06-13", "time": "15:00 ET", "team1": "Qatar", "team2": "Switzerland", "venue": "Levi's Stadium, Santa Clara"},
    {"match": 7, "stage": "Group Stage", "group": "C", "date": "2026-06-13", "time": "18:00 ET", "team1": "Brazil", "team2": "Morocco", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 8, "stage": "Group Stage", "group": "C", "date": "2026-06-13", "time": "21:00 ET", "team1": "Haiti", "team2": "Scotland", "venue": "Gillette Stadium, Foxborough"},
    {"match": 9, "stage": "Group Stage", "group": "E", "date": "2026-06-14", "time": "13:00 ET", "team1": "Germany", "team2": "Curacao", "venue": "NRG Stadium, Houston"},
    {"match": 10, "stage": "Group Stage", "group": "F", "date": "2026-06-14", "time": "16:00 ET", "team1": "Netherlands", "team2": "Japan", "venue": "AT&T Stadium, Arlington"},
    {"match": 11, "stage": "Group Stage", "group": "E", "date": "2026-06-14", "time": "19:00 ET", "team1": "Ivory Coast", "team2": "Ecuador", "venue": "Lincoln Financial Field, Philadelphia"},
    {"match": 12, "stage": "Group Stage", "group": "F", "date": "2026-06-14", "time": "22:00 ET", "team1": "Tunisia", "team2": "Sweden", "venue": "Estadio BBVA, Monterrey"},
    {"match": 13, "stage": "Group Stage", "group": "H", "date": "2026-06-15", "time": "12:00 ET", "team1": "Spain", "team2": "Cape Verde", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 14, "stage": "Group Stage", "group": "G", "date": "2026-06-15", "time": "15:00 ET", "team1": "Belgium", "team2": "Egypt", "venue": "Lumen Field, Seattle"},
    {"match": 15, "stage": "Group Stage", "group": "H", "date": "2026-06-15", "time": "18:00 ET", "team1": "Saudi Arabia", "team2": "Uruguay", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 16, "stage": "Group Stage", "group": "G", "date": "2026-06-15", "time": "21:00 ET", "team1": "Iran", "team2": "New Zealand", "venue": "SoFi Stadium, Inglewood"},
    {"match": 17, "stage": "Group Stage", "group": "J", "date": "2026-06-16", "time": "00:00 ET", "team1": "Austria", "team2": "Jordan", "venue": "Levi's Stadium, Santa Clara"},
    {"match": 18, "stage": "Group Stage", "group": "I", "date": "2026-06-16", "time": "15:00 ET", "team1": "France", "team2": "Senegal", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 19, "stage": "Group Stage", "group": "I", "date": "2026-06-16", "time": "18:00 ET", "team1": "Norway", "team2": "Iraq", "venue": "Gillette Stadium, Foxborough"},
    {"match": 20, "stage": "Group Stage", "group": "J", "date": "2026-06-16", "time": "21:00 ET", "team1": "Argentina", "team2": "Algeria", "venue": "GEHA Field at Arrowhead, Kansas City"},
    {"match": 21, "stage": "Group Stage", "group": "K", "date": "2026-06-17", "time": "13:00 ET", "team1": "Portugal", "team2": "DR Congo", "venue": "NRG Stadium, Houston"},
    {"match": 22, "stage": "Group Stage", "group": "L", "date": "2026-06-17", "time": "16:00 ET", "team1": "England", "team2": "Croatia", "venue": "AT&T Stadium, Arlington"},
    {"match": 23, "stage": "Group Stage", "group": "L", "date": "2026-06-17", "time": "19:00 ET", "team1": "Ghana", "team2": "Panama", "venue": "BMO Field, Toronto"},
    {"match": 24, "stage": "Group Stage", "group": "K", "date": "2026-06-17", "time": "22:00 ET", "team1": "Uzbekistan", "team2": "Colombia", "venue": "Estadio Azteca, Mexico City"},
    {"match": 25, "stage": "Group Stage", "group": "A", "date": "2026-06-18", "time": "12:00 ET", "team1": "South Africa", "team2": "Czech Republic", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 26, "stage": "Group Stage", "group": "B", "date": "2026-06-18", "time": "15:00 ET", "team1": "Switzerland", "team2": "Bosnia & Herzegovina", "venue": "SoFi Stadium, Inglewood"},
    {"match": 27, "stage": "Group Stage", "group": "B", "date": "2026-06-18", "time": "18:00 ET", "team1": "Canada", "team2": "Qatar", "venue": "BC Place, Vancouver"},
    {"match": 28, "stage": "Group Stage", "group": "A", "date": "2026-06-18", "time": "21:00 ET", "team1": "Mexico", "team2": "South Korea", "venue": "Estadio Akron, Guadalajara"},
    {"match": 29, "stage": "Group Stage", "group": "D", "date": "2026-06-19", "time": "00:00 ET", "team1": "Paraguay", "team2": "Turkey", "venue": "Levi's Stadium, Santa Clara"},
    {"match": 30, "stage": "Group Stage", "group": "C", "date": "2026-06-19", "time": "15:00 ET", "team1": "Scotland", "team2": "Morocco", "venue": "Gillette Stadium, Foxborough"},
    {"match": 31, "stage": "Group Stage", "group": "D", "date": "2026-06-19", "time": "15:00 ET", "team1": "United States", "team2": "Australia", "venue": "Lumen Field, Seattle"},
    {"match": 32, "stage": "Group Stage", "group": "C", "date": "2026-06-19", "time": "21:00 ET", "team1": "Brazil", "team2": "Haiti", "venue": "Lincoln Financial Field, Philadelphia"},
    {"match": 33, "stage": "Group Stage", "group": "F", "date": "2026-06-20", "time": "00:00 ET", "team1": "Tunisia", "team2": "Japan", "venue": "Estadio BBVA, Monterrey"},
    {"match": 34, "stage": "Group Stage", "group": "F", "date": "2026-06-20", "time": "13:00 ET", "team1": "Netherlands", "team2": "Sweden", "venue": "NRG Stadium, Houston"},
    {"match": 35, "stage": "Group Stage", "group": "E", "date": "2026-06-20", "time": "16:00 ET", "team1": "Germany", "team2": "Ivory Coast", "venue": "BMO Field, Toronto"},
    {"match": 36, "stage": "Group Stage", "group": "E", "date": "2026-06-20", "time": "20:00 ET", "team1": "Ecuador", "team2": "Curacao", "venue": "GEHA Field at Arrowhead, Kansas City"},
    {"match": 37, "stage": "Group Stage", "group": "H", "date": "2026-06-21", "time": "12:00 ET", "team1": "Spain", "team2": "Saudi Arabia", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 38, "stage": "Group Stage", "group": "G", "date": "2026-06-21", "time": "15:00 ET", "team1": "Belgium", "team2": "Iran", "venue": "SoFi Stadium, Inglewood"},
    {"match": 39, "stage": "Group Stage", "group": "H", "date": "2026-06-21", "time": "18:00 ET", "team1": "Uruguay", "team2": "Cape Verde", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 40, "stage": "Group Stage", "group": "G", "date": "2026-06-21", "time": "21:00 ET", "team1": "New Zealand", "team2": "Egypt", "venue": "BC Place, Vancouver"},
    {"match": 41, "stage": "Group Stage", "group": "J", "date": "2026-06-22", "time": "13:00 ET", "team1": "Argentina", "team2": "Austria", "venue": "AT&T Stadium, Arlington"},
    {"match": 42, "stage": "Group Stage", "group": "I", "date": "2026-06-22", "time": "17:00 ET", "team1": "France", "team2": "Iraq", "venue": "Lincoln Financial Field, Philadelphia"},
    {"match": 43, "stage": "Group Stage", "group": "I", "date": "2026-06-22", "time": "20:00 ET", "team1": "Norway", "team2": "Senegal", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 44, "stage": "Group Stage", "group": "J", "date": "2026-06-22", "time": "23:00 ET", "team1": "Jordan", "team2": "Algeria", "venue": "Levi's Stadium, Santa Clara"},
    {"match": 45, "stage": "Group Stage", "group": "K", "date": "2026-06-23", "time": "13:00 ET", "team1": "Portugal", "team2": "Uzbekistan", "venue": "NRG Stadium, Houston"},
    {"match": 46, "stage": "Group Stage", "group": "L", "date": "2026-06-23", "time": "16:00 ET", "team1": "England", "team2": "Ghana", "venue": "Gillette Stadium, Foxborough"},
    {"match": 47, "stage": "Group Stage", "group": "L", "date": "2026-06-23", "time": "19:00 ET", "team1": "Panama", "team2": "Croatia", "venue": "BMO Field, Toronto"},
    {"match": 48, "stage": "Group Stage", "group": "K", "date": "2026-06-23", "time": "22:00 ET", "team1": "Colombia", "team2": "DR Congo", "venue": "Estadio Akron, Guadalajara"},
    {"match": 49, "stage": "Group Stage", "group": "B", "date": "2026-06-24", "time": "15:00 ET", "team1": "Canada", "team2": "Switzerland", "venue": "BC Place, Vancouver"},
    {"match": 50, "stage": "Group Stage", "group": "B", "date": "2026-06-24", "time": "15:00 ET", "team1": "Qatar", "team2": "Bosnia & Herzegovina", "venue": "Lumen Field, Seattle"},
    {"match": 51, "stage": "Group Stage", "group": "C", "date": "2026-06-24", "time": "18:00 ET", "team1": "Scotland", "team2": "Brazil", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 52, "stage": "Group Stage", "group": "C", "date": "2026-06-24", "time": "18:00 ET", "team1": "Morocco", "team2": "Haiti", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 53, "stage": "Group Stage", "group": "A", "date": "2026-06-24", "time": "21:00 ET", "team1": "Mexico", "team2": "Czech Republic", "venue": "Estadio Azteca, Mexico City"},
    {"match": 54, "stage": "Group Stage", "group": "A", "date": "2026-06-24", "time": "21:00 ET", "team1": "South Korea", "team2": "South Africa", "venue": "Estadio BBVA, Monterrey"},
    {"match": 55, "stage": "Group Stage", "group": "E", "date": "2026-06-25", "time": "16:00 ET", "team1": "Ecuador", "team2": "Germany", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 56, "stage": "Group Stage", "group": "E", "date": "2026-06-25", "time": "16:00 ET", "team1": "Curacao", "team2": "Ivory Coast", "venue": "Lincoln Financial Field, Philadelphia"},
    {"match": 57, "stage": "Group Stage", "group": "F", "date": "2026-06-25", "time": "19:00 ET", "team1": "Tunisia", "team2": "Netherlands", "venue": "GEHA Field at Arrowhead, Kansas City"},
    {"match": 58, "stage": "Group Stage", "group": "F", "date": "2026-06-25", "time": "19:00 ET", "team1": "Japan", "team2": "Sweden", "venue": "AT&T Stadium, Arlington"},
    {"match": 59, "stage": "Group Stage", "group": "D", "date": "2026-06-25", "time": "22:00 ET", "team1": "United States", "team2": "Turkey", "venue": "SoFi Stadium, Inglewood"},
    {"match": 60, "stage": "Group Stage", "group": "D", "date": "2026-06-25", "time": "22:00 ET", "team1": "Paraguay", "team2": "Australia", "venue": "Levi's Stadium, Santa Clara"},
    {"match": 61, "stage": "Group Stage", "group": "I", "date": "2026-06-26", "time": "15:00 ET", "team1": "Norway", "team2": "France", "venue": "Gillette Stadium, Foxborough"},
    {"match": 62, "stage": "Group Stage", "group": "I", "date": "2026-06-26", "time": "15:00 ET", "team1": "Senegal", "team2": "Iraq", "venue": "BMO Field, Toronto"},
    {"match": 63, "stage": "Group Stage", "group": "H", "date": "2026-06-26", "time": "20:00 ET", "team1": "Uruguay", "team2": "Spain", "venue": "Estadio Akron, Guadalajara"},
    {"match": 64, "stage": "Group Stage", "group": "H", "date": "2026-06-26", "time": "20:00 ET", "team1": "Cape Verde", "team2": "Saudi Arabia", "venue": "NRG Stadium, Houston"},
    {"match": 65, "stage": "Group Stage", "group": "G", "date": "2026-06-26", "time": "23:00 ET", "team1": "New Zealand", "team2": "Belgium", "venue": "BC Place, Vancouver"},
    {"match": 66, "stage": "Group Stage", "group": "G", "date": "2026-06-26", "time": "23:00 ET", "team1": "Egypt", "team2": "Iran", "venue": "Lumen Field, Seattle"},
    {"match": 67, "stage": "Group Stage", "group": "L", "date": "2026-06-27", "time": "17:00 ET", "team1": "Panama", "team2": "England", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 68, "stage": "Group Stage", "group": "L", "date": "2026-06-27", "time": "17:00 ET", "team1": "Croatia", "team2": "Ghana", "venue": "Lincoln Financial Field, Philadelphia"},
    {"match": 69, "stage": "Group Stage", "group": "K", "date": "2026-06-27", "time": "19:30 ET", "team1": "Colombia", "team2": "Portugal", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 70, "stage": "Group Stage", "group": "K", "date": "2026-06-27", "time": "19:30 ET", "team1": "Uzbekistan", "team2": "DR Congo", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 71, "stage": "Group Stage", "group": "J", "date": "2026-06-27", "time": "22:00 ET", "team1": "Jordan", "team2": "Argentina", "venue": "AT&T Stadium, Arlington"},
    {"match": 72, "stage": "Group Stage", "group": "J", "date": "2026-06-27", "time": "22:00 ET", "team1": "Algeria", "team2": "Austria", "venue": "GEHA Field at Arrowhead, Kansas City"},
    {"match": 73, "stage": "Round of 32", "group": "", "date": "2026-06-28", "time": "15:00 ET", "team1": "2A", "team2": "2B", "venue": "SoFi Stadium, Inglewood"},
    {"match": 74, "stage": "Round of 32", "group": "", "date": "2026-06-29", "time": "13:00 ET", "team1": "1E", "team2": "3A/B/C/D/F", "venue": "NRG Stadium, Houston"},
    {"match": 75, "stage": "Round of 32", "group": "", "date": "2026-06-29", "time": "16:30 ET", "team1": "1F", "team2": "2C", "venue": "Gillette Stadium, Foxborough"},
    {"match": 76, "stage": "Round of 32", "group": "", "date": "2026-06-29", "time": "21:00 ET", "team1": "1C", "team2": "2F", "venue": "Estadio BBVA, Monterrey"},
    {"match": 77, "stage": "Round of 32", "group": "", "date": "2026-06-30", "time": "13:00 ET", "team1": "1I", "team2": "3C/D/F/G/H", "venue": "AT&T Stadium, Arlington"},
    {"match": 78, "stage": "Round of 32", "group": "", "date": "2026-06-30", "time": "17:00 ET", "team1": "2E", "team2": "2I", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 79, "stage": "Round of 32", "group": "", "date": "2026-06-30", "time": "21:00 ET", "team1": "1A", "team2": "3C/E/F/H/I", "venue": "Estadio Azteca, Mexico City"},
    {"match": 80, "stage": "Round of 32", "group": "", "date": "2026-07-01", "time": "12:00 ET", "team1": "1L", "team2": "3E/H/I/J/K", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 81, "stage": "Round of 32", "group": "", "date": "2026-07-01", "time": "16:00 ET", "team1": "1D", "team2": "3B/E/F/I/J", "venue": "Lumen Field, Seattle"},
    {"match": 82, "stage": "Round of 32", "group": "", "date": "2026-07-01", "time": "20:00 ET", "team1": "1G", "team2": "3A/E/H/I/J", "venue": "Levi's Stadium, Santa Clara"},
    {"match": 83, "stage": "Round of 32", "group": "", "date": "2026-07-02", "time": "15:00 ET", "team1": "2K", "team2": "2L", "venue": "SoFi Stadium, Inglewood"},
    {"match": 84, "stage": "Round of 32", "group": "", "date": "2026-07-02", "time": "19:00 ET", "team1": "1H", "team2": "2J", "venue": "BMO Field, Toronto"},
    {"match": 85, "stage": "Round of 32", "group": "", "date": "2026-07-02", "time": "23:00 ET", "team1": "1B", "team2": "3E/F/G/I/J", "venue": "BC Place, Vancouver"},
    {"match": 86, "stage": "Round of 32", "group": "", "date": "2026-07-03", "time": "14:00 ET", "team1": "1J", "team2": "2H", "venue": "AT&T Stadium, Arlington"},
    {"match": 87, "stage": "Round of 32", "group": "", "date": "2026-07-03", "time": "18:00 ET", "team1": "1K", "team2": "3D/E/I/J/L", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 88, "stage": "Round of 32", "group": "", "date": "2026-07-03", "time": "21:30 ET", "team1": "2D", "team2": "2G", "venue": "GEHA Field at Arrowhead, Kansas City"},
    {"match": 89, "stage": "Round of 16", "group": "", "date": "2026-07-04", "time": "13:00 ET", "team1": "Winner 74", "team2": "Winner 77", "venue": "NRG Stadium, Houston"},
    {"match": 90, "stage": "Round of 16", "group": "", "date": "2026-07-04", "time": "17:00 ET", "team1": "Winner 73", "team2": "Winner 75", "venue": "Lincoln Financial Field, Philadelphia"},
    {"match": 91, "stage": "Round of 16", "group": "", "date": "2026-07-05", "time": "16:00 ET", "team1": "Winner 76", "team2": "Winner 78", "venue": "MetLife Stadium, East Rutherford"},
    {"match": 92, "stage": "Round of 16", "group": "", "date": "2026-07-05", "time": "20:00 ET", "team1": "Winner 79", "team2": "Winner 80", "venue": "Estadio Azteca, Mexico City"},
    {"match": 93, "stage": "Round of 16", "group": "", "date": "2026-07-06", "time": "15:00 ET", "team1": "Winner 83", "team2": "Winner 84", "venue": "AT&T Stadium, Arlington"},
    {"match": 94, "stage": "Round of 16", "group": "", "date": "2026-07-06", "time": "20:00 ET", "team1": "Winner 81", "team2": "Winner 82", "venue": "Lumen Field, Seattle"},
    {"match": 95, "stage": "Round of 16", "group": "", "date": "2026-07-07", "time": "12:00 ET", "team1": "Winner 86", "team2": "Winner 88", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 96, "stage": "Round of 16", "group": "", "date": "2026-07-07", "time": "16:00 ET", "team1": "Winner 85", "team2": "Winner 87", "venue": "BC Place, Vancouver"},
    {"match": 97, "stage": "Quarter-Finals", "group": "", "date": "2026-07-09", "time": "16:00 ET", "team1": "Winner 89", "team2": "Winner 90", "venue": "Gillette Stadium, Foxborough"},
    {"match": 98, "stage": "Quarter-Finals", "group": "", "date": "2026-07-10", "time": "15:00 ET", "team1": "Winner 93", "team2": "Winner 94", "venue": "SoFi Stadium, Inglewood"},
    {"match": 99, "stage": "Quarter-Finals", "group": "", "date": "2026-07-11", "time": "17:00 ET", "team1": "Winner 91", "team2": "Winner 92", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 100, "stage": "Quarter-Finals", "group": "", "date": "2026-07-11", "time": "21:00 ET", "team1": "Winner 95", "team2": "Winner 96", "venue": "GEHA Field at Arrowhead, Kansas City"},
    {"match": 101, "stage": "Semi-Finals", "group": "", "date": "2026-07-14", "time": "15:00 ET", "team1": "Winner 97", "team2": "Winner 98", "venue": "AT&T Stadium, Arlington"},
    {"match": 102, "stage": "Semi-Finals", "group": "", "date": "2026-07-15", "time": "15:00 ET", "team1": "Winner 99", "team2": "Winner 100", "venue": "Mercedes-Benz Stadium, Atlanta"},
    {"match": 103, "stage": "Third Place", "group": "", "date": "2026-07-18", "time": "17:00 ET", "team1": "Loser 101", "team2": "Loser 102", "venue": "Hard Rock Stadium, Miami Gardens"},
    {"match": 104, "stage": "Final", "group": "", "date": "2026-07-19", "time": "15:00 ET", "team1": "Winner 101", "team2": "Winner 102", "venue": "MetLife Stadium, East Rutherford"},
]
